/** Medical Coding Services pillar page — copy from content brief */

export const mcsWhyAccurate = [
  {
    title: "Revenue",
    desc: "Coding accuracy directly determines reimbursement amounts. Undercoding leaves earned revenue uncollected; overcoding creates compliance and audit risk. Getting it right the first time is the difference between predictable revenue and constant correction.",
  },
  {
    title: "Compliance",
    desc: "Payers — especially Medicare and Medicaid — actively monitor coding patterns for irregularities. Consistent, well-documented coding practices are a core part of staying compliant with payer and regulatory requirements.",
  },
  {
    title: "Audits",
    desc: "Coding errors, especially patterns of errors, increase the likelihood of a payer audit. Clean, well-documented coding practices reduce that exposure significantly.",
  },
  {
    title: "Claim Approval",
    desc: "Clean, accurate codes are far more likely to be accepted on first submission, reducing the delays and administrative cost of resubmission and appeals.",
  },
  {
    title: "Risk Reduction",
    desc: "Systematic coding errors — whether from outdated knowledge or inconsistent review — create both financial and legal risk over time, particularly if audits reveal a pattern rather than an isolated mistake.",
  },
  {
    title: "Provider Documentation",
    desc: "Coding accuracy is only as good as the documentation behind it. Strong coding practices often surface documentation gaps early, before they become a bigger problem at audit time.",
  },
  {
    title: "Patient Records",
    desc: "Accurate coding contributes to a more reliable, complete patient record — which matters for continuity of care, not just for billing.",
  },
  {
    title: "Regulatory Compliance",
    desc: "Coding practices need to reflect current CMS guidelines and payer-specific rules, which are updated regularly and require ongoing attention to stay compliant.",
  },
  {
    title: "Financial Performance",
    desc: "Taken together, all of the above roll up into one outcome: how much of the revenue your practice has earned is actually collected, and how reliably.",
  },
] as const;

export const mcsChallenges = [
  {
    title: "Coding errors",
    desc: "Incorrect code selection, mismatched diagnosis-to-procedure pairing, or outdated code usage.",
  },
  {
    title: "Documentation gaps",
    desc: "Clinical notes that don't fully support the level of service or complexity being billed.",
  },
  {
    title: "Upcoding",
    desc: "Billing for a higher level of service than what was documented or performed, whether intentional or accidental — a significant compliance risk.",
  },
  {
    title: "Downcoding",
    desc: "Billing for a lower level of service than what was actually documented, resulting in underpayment for care that was properly provided.",
  },
  {
    title: "Denied claims",
    desc: "Often traced directly back to coding inaccuracies, missing modifiers, or documentation mismatches.",
  },
  {
    title: "Changing payer rules",
    desc: "CPT, ICD-10, and HCPCS updates happen on a regular cycle, and payer-specific rules shift independently of those updates.",
  },
  {
    title: "Compliance risks",
    desc: "Patterns of coding errors that increase audit exposure or trigger payer scrutiny.",
  },
  {
    title: "Audits",
    desc: "Both routine and triggered audits require coding practices that can withstand scrutiny.",
  },
  {
    title: "Missed revenue",
    desc: "Services performed but not fully or correctly captured in coding, resulting in silent underpayment.",
  },
  {
    title: "Coder shortages",
    desc: "Many practices struggle to hire and retain coders with current, specialty-specific certification and knowledge.",
  },
] as const;

export const mcsProcess = [
  {
    step: "01",
    title: "Patient Encounter",
    desc: "The clinical encounter takes place, and documentation is generated by the provider.",
  },
  {
    step: "02",
    title: "Clinical Documentation Review",
    desc: "Our coders review the documentation to confirm it supports the level of service and complexity that will be billed.",
  },
  {
    step: "03",
    title: "Code Assignment",
    desc: "CPT, ICD-10-CM, and HCPCS Level II codes are assigned based on the documented diagnosis and services, following current coding guidelines.",
  },
  {
    step: "04",
    title: "Quality Assurance",
    desc: "A second-level review checks for accuracy, code-pairing logic, and modifier correctness before the claim moves forward.",
  },
  {
    step: "05",
    title: "Compliance Review",
    desc: "Coding is checked against current CMS and payer-specific compliance requirements to reduce audit and denial risk.",
  },
  {
    step: "06",
    title: "Claim Readiness",
    desc: "Once coding passes quality and compliance review, the claim is prepared and handed off for submission.",
  },
  {
    step: "07",
    title: "Submission Support",
    desc: "We coordinate directly with billing workflows to ensure coded claims move smoothly into submission without delay.",
  },
  {
    step: "08",
    title: "Continuous Monitoring",
    desc: "Coding patterns, denial trends, and payer feedback are reviewed on an ongoing basis to catch recurring issues early and adjust as guidelines change.",
  },
] as const;

export const mcsIncluded = [
  {
    title: "CPT Coding",
    desc: "Accurate procedural coding across evaluation & management (E/M), surgical, diagnostic, and specialty-specific services, aligned with current CPT guidelines.",
  },
  {
    title: "ICD-10 Coding",
    desc: "Diagnosis coding that accurately reflects documented clinical conditions and supports the medical necessity of billed services.",
  },
  {
    title: "HCPCS Coding",
    desc: "Coding for durable medical equipment, supplies, and services not captured under CPT — particularly relevant for Medicare and Medicaid claims.",
  },
  {
    title: "Risk Adjustment Coding",
    desc: "Support for risk-adjustment-relevant coding accuracy, important for practices participating in value-based care or Medicare Advantage risk models, where diagnosis coding completeness directly affects risk scores.",
  },
  {
    title: "Coding Audits",
    desc: "Structured review of existing coding practices to identify error patterns, compliance gaps, and revenue leakage before they become bigger problems.",
  },
  {
    title: "Coding Compliance",
    desc: "Ongoing alignment with CMS guidelines and payer-specific requirements, reducing audit exposure and denial risk.",
  },
  {
    title: "Documentation Review",
    desc: "Feedback on clinical documentation quality, helping providers understand where notes may need more detail to support the codes being billed.",
  },
  {
    title: "Coding Quality Assurance",
    desc: "A structured second-level review process built into every coding cycle, not just applied periodically.",
  },
  {
    title: "Modifier Review",
    desc: "Careful application of modifiers — a frequent, avoidable source of denials when handled inconsistently.",
  },
  {
    title: "Specialty Coding",
    desc: "Coders trained specifically in the coding nuances of individual specialties, rather than applying a generalized coding approach across every practice type.",
  },
  {
    title: "Coding Error Resolution",
    desc: "When errors are identified — whether through internal QA or payer feedback — we correct and address the root cause, not just the individual claim.",
  },
  {
    title: "Coding Consultation",
    desc: "Ongoing guidance for practices that want to strengthen internal documentation and coding practices, whether or not full outsourcing is the right fit.",
  },
] as const;

export const mcsSpecialties = [
  {
    title: "Mental Health",
    desc: "Time-based CPT codes for therapy sessions require precise documentation of session length and content, with medical necessity closely reviewed by payers.",
  },
  {
    title: "Behavioral Health",
    desc: "Bundled service arrangements and program-based billing require coding that reflects treatment plans accurately, often with authorization dependencies.",
  },
  {
    title: "Psychiatry",
    desc: "Coding frequently combines evaluation & management codes with psychotherapy add-on codes, requiring clear documentation of both components within a single encounter.",
  },
  {
    title: "Family Medicine",
    desc: "High-volume, high-variety visits — preventive care, chronic condition management, acute concerns — require coders comfortable moving across a broad range of code categories accurately.",
  },
  {
    title: "Internal Medicine",
    desc: "Complex, often multi-condition visits require careful attention to E/M level selection and accurate diagnosis-to-service pairing.",
  },
  {
    title: "Cardiology",
    desc: "Diagnostic testing, procedural coding, and modifier use are all more complex here, with frequent updates to cardiology-specific CPT guidance.",
  },
  {
    title: "Orthopedics",
    desc: "Surgical bundling rules and global period tracking require coders who understand how post-operative care is bundled versus separately billable.",
  },
  {
    title: "Pain Management",
    desc: "Procedure-heavy coding with frequent use of modifiers and close payer scrutiny around medical necessity for interventional procedures.",
  },
  {
    title: "Urgent Care",
    desc: "High patient volume and same-day turnaround require efficient but accurate level-of-service coding under time pressure.",
  },
  {
    title: "Primary Care",
    desc: "Preventive care coding, chronic care management codes, and annual wellness visit coding each carry their own specific documentation requirements.",
  },
  {
    title: "Dental",
    desc: "Crossover coding between medical and dental insurance is a common source of confusion and denials, requiring familiarity with both systems.",
  },
  {
    title: "Behavioral Medicine",
    desc: "Overlapping physical and behavioral health coding requires coordination between medical and behavioral code sets within the same treatment context.",
  },
] as const;

export const mcsCompare = [
  {
    factor: "Cost",
    inHouse: "Salaries, benefits, ongoing training regardless of claim volume",
    outsourced: "Scales with actual coding volume and need",
  },
  {
    factor: "Accuracy",
    inHouse: "Dependent on individual coder knowledge and availability",
    outsourced: "Backed by structured QA and peer review processes",
  },
  {
    factor: "Compliance",
    inHouse: "Requires internal tracking of every CMS and payer rule update",
    outsourced: "Compliance monitoring built into the coding workflow",
  },
  {
    factor: "Scalability",
    inHouse: "Adding capacity requires hiring and training",
    outsourced: "Capacity can adjust with practice growth or volume changes",
  },
  {
    factor: "Productivity",
    inHouse: "Coders often juggle multiple administrative responsibilities",
    outsourced: "Dedicated coders focused solely on coding accuracy",
  },
  {
    factor: "Training",
    inHouse: "Ongoing internal investment in certification and education",
    outsourced: "Training and certification maintained as part of the service",
  },
  {
    factor: "Technology",
    inHouse: "Requires internal investment in coding software and updates",
    outsourced: "Coding tools and updates managed as part of the service",
  },
  {
    factor: "Expertise",
    inHouse: "Limited to the specialties your internal team happens to know well",
    outsourced: "Access to coders experienced across multiple specialties",
  },
  {
    factor: "Turnaround",
    inHouse: "Dependent on internal staff bandwidth and workload",
    outsourced: "Structured turnaround times built into the process",
  },
  {
    factor: "Revenue Impact",
    inHouse: "Errors may go unnoticed without dedicated QA review",
    outsourced: "Structured review process designed to catch revenue-impacting errors",
  },
] as const;

export const mcsWhy = [
  {
    title: "Dedicated Coders",
    desc: "Your practice works with coders who become familiar with your documentation style, specialty, and payer mix over time — not a rotating pool of generalists.",
  },
  {
    title: "Certified Team",
    desc: "Our coding staff hold relevant industry certifications and stay current on CPT, ICD-10-CM, and HCPCS Level II updates as they're released.",
  },
  {
    title: "HIPAA Compliance",
    desc: "Every stage of the coding process — from documentation review to code assignment — is handled under HIPAA-compliant workflows, with signed Business Associate Agreements for every client.",
  },
  {
    title: "Transparent Reporting",
    desc: "You have visibility into coding accuracy trends, denial patterns tied to coding, and quality assurance outcomes — not just a black-box coding function.",
  },
  {
    title: "Coding Accuracy",
    desc: "Every code is reviewed against documentation before it moves forward, reducing both denial risk and underbilling.",
  },
  {
    title: "Quality Reviews",
    desc: "A structured, second-level QA process is built into our coding workflow as standard practice, not an occasional check.",
  },
  {
    title: "Compliance Focus",
    desc: "Coding practices are actively monitored against current CMS guidelines and payer-specific requirements to reduce audit exposure.",
  },
  {
    title: "Specialty Expertise",
    desc: "Coders with specific training in mental health, behavioral health, and a range of other specialties, rather than a one-size-fits-all coding approach.",
  },
  {
    title: "Latest Coding Updates",
    desc: "Our team stays current on annual and mid-year CPT, ICD-10-CM, and HCPCS updates, so your coding reflects the most current guidelines.",
  },
  {
    title: "Scalable Services",
    desc: "Whether you're a solo practitioner or a growing multi-location group, coding capacity adjusts to match your practice's actual volume.",
  },
] as const;

export const mcsRcmLinks = [
  {
    title: "Claims",
    desc: "Accurate coding is what makes a clean claim possible in the first place; inaccurate coding creates denial risk before a claim is even submitted.",
  },
  {
    title: "Billing",
    desc: "Billing teams can only submit what coding provides them; coding errors become billing problems immediately.",
  },
  {
    title: "Collections",
    desc: "Underpayment tied to undercoding, or denials tied to coding mismatches, directly affect how much revenue is ultimately collected.",
  },
  {
    title: "Denials",
    desc: "A significant share of claim denials trace back to coding issues — mismatched diagnosis and procedure codes, missing modifiers, or insufficient documentation support.",
  },
  {
    title: "Cash Flow",
    desc: "Clean, accurate coding reduces the back-and-forth of resubmission and appeals, which shortens the time between service delivery and payment.",
  },
  {
    title: "Compliance",
    desc: "Coding accuracy is one of the most closely scrutinized components of healthcare compliance, given its direct link to reimbursement.",
  },
] as const;

export const mcsIndustries = [
  "Physicians and physician groups",
  "Clinics and outpatient facilities",
  "Hospitals and healthcare systems",
  "Behavioral health organizations",
  "Mental health practices",
  "Dental practices",
  "Urgent care centers",
  "Multi-location practices",
  "Private practices",
  "Healthcare groups and organizations",
] as const;

export const mcsRelated = [
  {
    title: "Medical Billing Services",
    href: "/medical-billing-services",
    desc: "The full billing operation that coding feeds into, from charge entry through payment posting.",
  },
  {
    title: "Revenue Cycle Management",
    href: "/revenue-cycle-management",
    desc: "A broader view of your entire financial process, from scheduling through final payment resolution.",
  },
  {
    title: "Claims Management Services",
    href: "/claims-management-services",
    desc: "End-to-end claim lifecycle management, built on the accurate coding foundation this page describes.",
  },
  {
    title: "Denial Management Services",
    href: "/denial-management-services",
    desc: "Focused resolution of denied claims, many of which trace back to coding-related issues.",
  },
] as const;

export const mcsFaqs: [string, string][] = [
  [
    "What are medical coding services?",
    "Medical coding services involve translating clinical documentation into standardized CPT, ICD-10-CM, and HCPCS Level II codes that accurately represent the diagnosis and services provided during a patient encounter, forming the foundation for accurate insurance claims.",
  ],
  [
    "What is the difference between medical billing and medical coding?",
    "Medical coding is the process of assigning standardized codes to a clinical encounter based on documentation. Medical billing uses those codes to create and submit claims to payers and manage them through to payment. Coding happens first and directly determines billing accuracy.",
  ],
  [
    "Why should I outsource medical coding?",
    "Outsourcing provides access to certified coders with current, specialty-specific knowledge, reduces the cost and risk of maintaining in-house coding expertise, and typically includes structured quality assurance review that catches errors before they become denials.",
  ],
  [
    "What is CPT coding?",
    "CPT (Current Procedural Terminology) coding describes the specific procedures and services a provider performed during a patient encounter, using a standardized code set maintained by the American Medical Association.",
  ],
  [
    "What is ICD-10 coding?",
    "ICD-10-CM coding describes the diagnosis or medical reason a service was provided, and must logically align with the procedure codes billed to support medical necessity and avoid denials.",
  ],
  [
    "What is HCPCS coding used for?",
    "HCPCS Level II codes are used primarily for durable medical equipment, certain medications, and services not covered under CPT, and are especially relevant for Medicare and Medicaid billing.",
  ],
  [
    "How does coding accuracy affect reimbursement?",
    "Payers reimburse based on what the submitted codes indicate, not on the care actually delivered. Undercoding results in lost revenue for services rightfully performed, while overcoding creates compliance and audit risk.",
  ],
  [
    "Do you provide coding audits?",
    "Yes, coding audits review existing coding practices to identify error patterns, documentation gaps, and compliance risks, providing a clear picture of where coding accuracy can be improved.",
  ],
  [
    "Are your medical coding services HIPAA compliant?",
    "Yes, our coding workflows are built around HIPAA compliance requirements, and we operate under signed Business Associate Agreements with every client.",
  ],
  [
    "What specialties do you provide medical coding for?",
    "We provide coding support across a range of specialties, including mental health, behavioral health, psychiatry, family medicine, internal medicine, cardiology, orthopedics, pain management, urgent care, primary care, and dental.",
  ],
  [
    "How much does outsourced medical coding cost?",
    "Pricing depends on claim volume, specialty complexity, and scope of service, and is typically discussed after an initial review of a practice's coding needs during a free coding audit.",
  ],
  [
    "What is risk adjustment coding?",
    "Risk adjustment coding refers to diagnosis coding accuracy that supports risk scoring in value-based care and Medicare Advantage models, where completeness and specificity of diagnosis coding directly affect risk-adjusted reimbursement.",
  ],
  [
    "What technology do you use for medical coding?",
    "Our coding workflow integrates with major practice management and EHR systems, supporting efficient documentation review and code assignment without requiring practices to change their existing systems.",
  ],
  [
    "How accurate is outsourced medical coding compared to in-house coding?",
    "Accuracy depends on the quality of the coding process, not simply whether coding is in-house or outsourced. A structured, multi-step review process with dedicated QA — like the one used here — is what drives consistent accuracy, regardless of where coding is performed.",
  ],
  [
    "What is the typical turnaround time for medical coding services?",
    "Turnaround time depends on claim volume and complexity, and is typically discussed and set as part of onboarding to align with a practice's existing billing timeline expectations.",
  ],
];
